### ISSUE TITLE
Code not executable on Linux-based environments

### ISSUE THREAD

**Issue by akotil** [BensonZhou1991/MCTS-New#1]
Hello,

the simulation/size folder contains `to_python.cp37-win_amd64.pyd` files, which are Windows dll files that cannot be executed on Linux-like environments. Is it possible to make the code executable in other systems?

Thank you.

**Comment by BensonZhou1991** [comment]
Hi Akotil,
These files are to implement the Simulation module of our MCTS framework and compiled from C++ using a few basic packages. If you want, you may leave your e-mail address here and I can send you the relevant source code. I believe it can easily be re-compiled to support Linux environments.

**Comment by akotil** [comment]
Hi,

Thank you for your response! I would very much appreciate the C++ files. My e-mail is: kotilayse@gmail.com
